### ISSUE TITLE
The type 'TraceWriter' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by pswetz** [tfsaggregator/aggregator-cli#6]
During rule execution.

2018-10-23T15:22:26.674 [Error] Function compilation error

Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.

   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader`1.GetFunctionTargetAsync[T](Int32 attemptCount) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionLoader.cs : 55

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2018-10-23T15:22:26.325 [Information] Executing 'Functions.testrule' (Reason='This function was programmatically called via the host APIs.', Id=ede53413-f440-4479-a8d6-fd90c1d1bfee)
2018-10-23T15:22:26.827 [Warning] run.csx(6,62): warning CS0618: 'TraceWriter' is obsolete: 'Will be removed in an upcoming version. Use Microsoft.Extensions.Logging.ILogger instead.'
2018-10-23T15:22:26.854 [Error] run.csx(8,23): error CS0012: The type 'TraceWriter' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by giuliov** [comment]
This is also fixed in commit 67f57d8f95a7bdafdc1ed62cbd2acabe105a01a9.
