### ISSUE TITLE
Aggregator fail with not implemeted 501 statuscode - on premise Azure DevOps 2019

### ISSUE THREAD

**Issue by mrweiland** [tfsaggregator/aggregator-cli#67]
I have setup a function instance in Azure with one simple rule. In my script i also add webhooks on my on premise Azure Devops 2019 instance. 

Everything works when i run a test webhook call but when i run a real hook on for example workitem.update i get this error. 

I changed the CLI code to give me more information on error.

```
λ  dotnet $aggregatorCli stream.logs --instance $aggregatorName --resourceGroup $resourceGroup --verbose
[2019-08-19 10:35:00Z] Aggregator CLI v0.9.0+local.development (build: 0.9.0.0 Debug) (c) TFS Aggregator Team
[2019-08-19 10:35:00Z] Authenticating to Azure...
[2019-08-19 10:35:01Z] Connected to subscription 20bba462-f2a0-435e-adb7-4d0f8d775e23
[2019-08-19 10:35:01Z] Connecting to FunctionWI6...
[2019-08-19 10:35:06Z] Connected to FunctionWI6 logs
[2019-08-19 10:35:18Z] Streaming FunctionWI6 logs...
2019-08-19T08:35:18  Welcome, you are now connected to log-streaming service.
2019-08-19T08:35:19.038 [Information] Executing 'Functions.writeworkitemtypeandtitle' (Reason='This function was programmatically called via the host APIs.', Id=ea3e2242-0905-4da4-959b-738146178263)
2019-08-19T08:35:19.038 [Information] Executing 'Functions.writeworkitemtypeandtitle' (Reason='This function was programmatically called via the host APIs.', Id=ea3e2242-0905-4da4-959b-738146178263)
2019-08-19T08:35:19.920 [Information] Aggregator v0.9.1+local.development executing rule 'writeworkitemtypeandtitle'
2019-08-19T08:35:20.092 [Warning] collectionUrl https://tfs-test.xxx.com/tfs/Test_XXXCareCollection/
2019-08-19T08:35:20.093 [Information] teamProjectId b328f48c-4979-4d71-9090-bae5966771bf
2019-08-19T08:35:20.093 [Information] workItem Microsoft.TeamFoundation.WorkItemTracking.WebApi.Models.WorkItem
2019-08-19T08:35:19.920 [Information] Aggregator v0.9.1+local.development executing rule 'writeworkitemtypeandtitle'
2019-08-19T08:35:20.092 [Warning] collectionUrl https://tfs-test.raysearchlabs.com/tfs/Test_xxxCareCollection/
2019-08-19T08:35:20.093 [Information] teamProjectId b328f48c-4979-4d71-9090-bae5966771bf
2019-08-19T08:35:20.093 [Information] workItem Microsoft.TeamFoundation.WorkItemTracking.WebApi.Models.WorkItem
2019-08-19T08:35:21.047 [Warning] Rule 'writeworkitemtypeandtitle' failed:    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at aggregator.RuleWrapper.ExecuteAsync(Uri collectionUri, Guid teamProjectId, WorkItem workItem, CancellationToken cancellationToken) in C:\git\aggregatorazuredevops\aggregator-cli\src\aggregator-function\RuleWrapper.cs:line 51
   at aggregator.AzureFunctionHandler.RunAsync(HttpRequestMessage req, CancellationToken cancellationToken) in C:\git\aggregatorazuredevops\aggregator-cli\src\aggregator-function\AzureFunctionHandler.cs:line 116
2019-08-19T08:35:21.088 [Information] Executed 'Functions.writeworkitemtypeandtitle' (Succeeded, Id=ea3e2242-0905-4da4-959b-738146178263)
2019-08-19T08:35:21.047 [Warning] Rule 'writeworkitemtypeandtitle' failed:    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at aggregator.RuleWrapper.ExecuteAsync(Uri collectionUri, Guid teamProjectId, WorkItem workItem, CancellationToken cancellationToken) in C:\git\aggregatorazuredevops\aggregator-cli\src\aggregator-function\RuleWrapper.cs:line 51
   at aggregator.AzureFunctionHandler.RunAsync(HttpRequestMessage req, CancellationToken cancellationToken) in C:\git\aggregatorazuredevops\aggregator-cli\src\aggregator-function\AzureFunctionHandler.cs:line 116
2019-08-19T08:35:21.088 [Information] Executed 'Functions.writeworkitemtypeandtitle' (Succeeded, Id=ea3e2242-0905-4da4-959b-738146178263)
2019-08-19T08:35:22.829 [Information] Host lock lease acquired by instance ID 'bec43f7473ffa1a31147948b5c1b6b8e'.
```

Here is the test call that works
![image](https://user-images.githubusercontent.com/12168854/63251198-8760c280-c26d-11e9-956d-2dc3dba5acad.png)

Here is the call from a real workitem
![image](https://user-images.githubusercontent.com/12168854/63251323-c4c55000-c26d-11e9-9ecc-617d3de2e6f6.png)

Here is the error in code in AzureFunctionHandler.cs
![image](https://user-images.githubusercontent.com/12168854/63251434-048c3780-c26e-11e9-94a5-174c82b17d14.png)

I also found on Azure function that Aggregator_VstsToken value is empty - isnt it here PAT token should be? I tried to put in my PAT token manually but it doesnt work either.
![image](https://user-images.githubusercontent.com/12168854/63251564-45844c00-c26e-11e9-8145-6886a7e5a73e.png)

I tried to debug the code and see why is this happening but cannot fix it. :( Can you please give me some advice.

**Comment by mrweiland** [comment]
I just fine read - its not supported yet. :(

**Comment by giuliov** [comment]
Correct. The general idea is to use the Azure Function runtime on-prem to host the Rule Engine. Sadly most of the CLI code won't work to set up the function and the hooks.

That said, looks like you are trying a different scenario. Your AzDO instance is accessible from internet which should (theoretically) work. It hasn't been tested, so no surprise it doesn't work at first, but maybe fixing is simple.
Two questions:
1. the SSL certificate comes from a public CA?
2. the hook sends the Full event message?

To debug, pull the code and launch the `aggregator-function` project in Visual Studio, and publish the port (7001 or so).

**Comment by mrweiland** [comment]
1. Yes the certificate are ok
2. Yes hooks send but fails. 

Trying to debug locally - how do i publish rules to local function? I got function up and running but hard to understand how to publish new rules. 


I got this powershell that is nice to have for everyone working with this i think.

```
$aggregatorCli  = where my new compiled aggregator are

$aggregatorName = "MyAggWI8"
$resourceGroup = "resourcegroup"
$location = "NorthEurope"
$aggregatorCli = "..\aggregator-cli\src\aggregator-cli\bin\debug\netcoreapp2.1\aggregator-cli.dll"
$subscriptionGuid = "guid"
$client = "guid"
$applicationPassword = "pass"
$tenant = "4d30cd81-8fb9-4df2-9ec2-7389fd472cbf"
$azureDevopsUrl = "https://tfs-test.xxx.com/tfs/Test_xxCollection"
$azureDevopsPAT = "PATTOKEN TO Azure  Devops on prem"
$azureDevOpsProjectName = "Project"

$ruleName = "writeworkitemtypeandtitle"

$ruleFilePath = "test\test1.rule"

dotnet $aggregatorCli logon.azure -s $subscriptionGuid -c $client -p $applicationPassword -t $tenant

dotnet $aggregatorCli logon.ado --url $azureDevopsUrl --mode PAT $azureDevopsPAT

dotnet $aggregatorCli install.instance --verbose --name $aggregatorName --resourceGroup $resourceGroup --location $location --requiredVersion 0.9.0

dotnet $aggregatorCli add.rule --verbose --instance $aggregatorName --name $ruleName --file $ruleFilePath --resourceGroup $resourceGroup

dotnet $aggregatorCli map.rule --verbose --project $azureDevOpsProjectName --event workitem.updated --instance $aggregatorName --resourceGroup $resourceGroup --rule $ruleName

dotnet $aggregatorCli map.rule --verbose --project $azureDevOpsProjectName --event workitem.created --instance $aggregatorName --resourceGroup $resourceGroup --rule $ruleName

```

**Comment by giuliov** [comment]
> how do i publish rules to local function?
simply create a folder in `src/aggregator-function/bin/Debug/netstandard2.0` with these three files:

- rule code in a file _rulename_`.rule` (e.g. `hello.rule` in folder `hello`)
- `function.json`
- `run.csx`

you must do this every time you press F5

function.json content:
```json
{
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "webHookType": "genericJson",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ],
  "disabled": false
}
```

run.csx content:
```csharp
#r "../bin/aggregator-function.dll"
#r "../bin/aggregator-shared.dll"

using aggregator;

public static async Task<object> Run(HttpRequestMessage req, ILogger logger, ExecutionContext context)
{
    var handler = new AzureFunctionHandler(logger, context);
    return await handler.Run(req);
}
```

**Comment by mrweiland** [comment]
Getting closer but i added test folder and test.rule under that folder:

**Postman call tested with**
```
http://0.0.0.0:7071/api/test1

http://0.0.0.0:7071/api/test/test1
```

When i run i get this
```
[2019-08-19 11:14:08] Executing HTTP request: {
[2019-08-19 11:14:08]   "requestId": "43173722-5831-4c9f-b727-20b488202792",
[2019-08-19 11:14:08]   "method": "GET",
[2019-08-19 11:14:08]   "uri": "/api/test1"
[2019-08-19 11:14:08] }
[2019-08-19 11:14:08] Executed HTTP request: {
[2019-08-19 11:14:08]   "requestId": "43173722-5831-4c9f-b727-20b488202792",
[2019-08-19 11:14:08]   "method": "GET",
[2019-08-19 11:14:08]   "uri": "/api/test1",
[2019-08-19 11:14:08]   "identities": [],
[2019-08-19 11:14:08]   "status": 404,
[2019-08-19 11:14:08]   "duration": 10
[2019-08-19 11:14:08] }
[2019-08-19 11:14:22] Executing HTTP request: {
[2019-08-19 11:14:22]   "requestId": "a0abd359-d411-443f-86a8-14e0ea65bad2",
[2019-08-19 11:14:22]   "method": "GET",
[2019-08-19 11:14:22]   "uri": "/api/test/test1"
[2019-08-19 11:14:22] }
[2019-08-19 11:14:22] Executed HTTP request: {
[2019-08-19 11:14:22]   "requestId": "a0abd359-d411-443f-86a8-14e0ea65bad2",
[2019-08-19 11:14:22]   "method": "GET",
[2019-08-19 11:14:22]   "uri": "/api/test/test1",
[2019-08-19 11:14:22]   "identities": [],
[2019-08-19 11:14:22]   "status": 404,
[2019-08-19 11:14:22]   "duration": 9
[2019-08-19 11:14:22] }
```

**Comment by mrweiland** [comment]
Also i added in post call our JSON from Workitem under Content

![image](https://user-images.githubusercontent.com/12168854/63261441-c7cb3b00-c283-11e9-9013-86c363b41fd7.png)

**Comment by mrweiland** [comment]
It doesnt seems to find my job functions?

```
[2019-08-19 11:24:40] Starting JobHost
[2019-08-19 11:24:40] Starting Host (HostId=se00157wks-1042972961, InstanceId=53ab2a74-9deb-4020-b48e-08155378c955, Version=2.0.12625.0, ProcessId=31968, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[2019-08-19 11:24:40] Loading functions metadata
[2019-08-19 11:24:40] 0 functions loaded
[2019-08-19 11:24:40] Generating 0 job function(s)
[2019-08-19 11:24:40] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[2019-08-19 11:24:40] Host initialized (65ms)
[2019-08-19 11:24:40] Host started (66ms)
[2019-08-19 11:24:40] Job host started
[2019-08-19 11:24:40] Host restarted.
[2019-08-19 11:24:40] Stopping JobHost
[2019-08-19 11:24:40] Job host stopped
[2019-08-19 11:24:45] Host lock lease acquired by instance ID '0000000000000000000000000DDC999E'.
```

**Comment by giuliov** [comment]
Exactly, you must copy the folder, _after_ you hit F5.
I do not have my dev machine at hand, so some detail can be imprecise, but I debug the engine launching the `aggregator-function` project in Visual Studio 2019, copy the folder with the three files and hitting the endpoint using Postman with previously captured messages.

**Comment by mrweiland** [comment]
Done that and it found my function - but the api call is little wrong i think

This is my function folder
![image](https://user-images.githubusercontent.com/12168854/63262350-fcd88d00-c285-11e9-9b45-05b342a70252.png)

This is my rules in test folder inside function
![image](https://user-images.githubusercontent.com/12168854/63262402-242f5a00-c286-11e9-84e1-521e40e19409.png)

When i run postman with api call `http://0.0.0.0:7071/api/test` it cannot found and run rule. hmm.

![image](https://user-images.githubusercontent.com/12168854/63262442-3e693800-c286-11e9-9ed0-d7f98c92a32f.png)

**Comment by giuliov** [comment]
all three files goes in the folder
the Function runtime discover them all

**Comment by mrweiland** [comment]
I found issue - i saw name on local function and changed folder to match that and now it works.

```
[2019-08-19 12:07:04] Initial WorkItem 55851 retrieved from https://tfs-test.xxxx.com/tfs/Test_xxxCollection
[2019-08-19 12:07:04] Executing Rule...
[2019-08-19 12:07:06] Rule succeeded with Hello Hazard #55851 - Fault Tree Template Manager Frontend!
[2019-08-19 12:07:06] No changes saved to Azure DevOps.
[2019-08-19 12:07:06] execResult Hello Hazard #55851 - Fault Tree Template Manager Frontend!
[2019-08-19 12:07:06] Returning 'Hello Hazard #55851 - Fault Tree Template Manager Frontend!' from 'testfunction'
[2019-08-19 12:07:06] Executed 'Functions.testfunction' (Succeeded, Id=84b411f0-c329-4446-b711-831c28042a73)
[2019-08-19 12:07:06] Executed HTTP request: {
[2019-08-19 12:07:06]   "requestId": "cc022a04-9658-4a6f-8468-e9ce436aa277",
[2019-08-19 12:07:06]   "method": "POST",
[2019-08-19 12:07:06]   "uri": "/api/testfunction",
[2019-08-19 12:07:06]   "identities": [
[2019-08-19 12:07:06]     {
[2019-08-19 12:07:06]       "type": "WebJobsAuthLevel",
[2019-08-19 12:07:06]       "level": "Admin"
[2019-08-19 12:07:06]     }
[2019-08-19 12:07:06]   ],
[2019-08-19 12:07:06]   "status": 200,
[2019-08-19 12:07:06]   "duration": 2531
[2019-08-19 12:07:06] }
```
Now i need to understand why it doesnt work from Azure function...
